// All content from HTCH_ARQUITECTURA_PWA.xlsx

export const seedSpaServices = [
  // Masajes y Terapias
  { category: "Masajes y Terapias", name: "Masaje Barro", description: "Fangoterapia: Barro termal, regenerador celular, nutre profundamente, tonifica y reafirma.", duration: "50 min", price: "$60.000", order: 1 },
  { category: "Masajes y Terapias", name: "Masaje Serenidad", description: "Con aromaterapia, relajante antiestrés, calma y alivia la fatiga.", duration: "30 / 50 min", price: "$30.000 / $50.000", order: 2 },
  { category: "Masajes y Terapias", name: "Masaje Recarga Vital", description: "Descontracturante, promueve la relajación muscular y alivia tensiones.", duration: "30 / 50 min", price: "$40.000 / $60.000", order: 3 },
  { category: "Masajes y Terapias", name: "Masaje Regenerativo", description: "Deportivo, activa la recuperación muscular y previene lesiones deportivas.", duration: "50 min", price: "$70.000", order: 4 },
  { category: "Masajes y Terapias", name: "Masaje Piedras Calientes", description: "Estimula la circulación, libera el estrés y mejora la calidad del sueño.", duration: "50 / 80 min", price: "$60.000 / $75.000", order: 5 },
  { category: "Masajes y Terapias", name: "Masaje Champi Hindú", description: "Relajante, despierta los sentidos, con aceites aromáticos y sonido de Thingshas.", duration: "30 / 50 min", price: "$40.000 / $50.000", order: 6 },
  { category: "Masajes y Terapias", name: "Masaje Alunco", description: "Relajante y descontracturante.", duration: "50 min", price: "$60.000", order: 7 },
  { category: "Masajes y Terapias", name: "Masaje Sueco", description: "Masaje de intensidad media, activa la circulación sanguínea y linfática.", duration: "50 / 80 min", price: "$60.000 / $75.000", order: 8 },
  { category: "Masajes y Terapias", name: "Masaje Relajante", description: "Masaje relajante con lavado y secado de pelo.", duration: "50 min", price: "$45.000", order: 9 },
  { category: "Masajes y Terapias", name: "Alunco Kids", description: "Relajante para niños entre 5 a 14 años. Efecto relajante y de calma.", duration: "30 min", price: "$35.000", order: 10 },
  { category: "Masajes y Terapias", name: "Reflexología Podal", description: "Alivia dolores y relaja el cuerpo.", duration: "30 min", price: "$45.000", order: 11 },
  { category: "Masajes y Terapias", name: "Relajante + Reflexología", description: "Combinación de técnicas de relajación y presión en puntos reflejos.", duration: "80 min", price: "$70.000", order: 12 },
  // Rituales de Renovación Corporal
  { category: "Rituales de Renovación", name: "Ritual Volcánico", description: "Masaje de manos, masaje con piedras calientes y toques de piedras frías. En puntos de la columna y piernas.", duration: "50 min", price: "$65.000", order: 1 },
  { category: "Rituales de Renovación", name: "Ritual Árbol de la Vida", description: "Masaje de pies, hombros y cabeza.", duration: "50 min", price: "$60.000", order: 2 },
  { category: "Rituales de Renovación", name: "Ritual Kundalini de Bosque", description: "Cuidado de la piel y masaje reconstituyente de espalda.", duration: "50 min", price: "$60.000", order: 3 },
  { category: "Rituales de Renovación", name: "Ritual Sabiduría de la Naturaleza", description: "Exfoliación facial, máscara nutritiva y masaje relajante corporal.", duration: "50 min", price: "$60.000", order: 4 },
  { category: "Rituales de Renovación", name: "Ritual Agua Curativa Détox", description: "Drenaje linfático, limpia toxinas y relaja la musculatura.", duration: "50 min", price: "$65.000", order: 5 },
  { category: "Rituales de Renovación", name: "Ritual del Montañista", description: "Reflexología pies y relajación piernas.", duration: "50 min", price: "$60.000", order: 6 },
  { category: "Rituales de Renovación", name: "Ritual Signature Termal Alunco", description: "Tratamiento corporal integral con barro termal: exfoliante, masaje e hidratación.", duration: "80 min", price: "$95.000", order: 7 },
  { category: "Rituales de Renovación", name: "Ritual del Chocolate", description: "Tina caliente y masaje relajante.", duration: "80 min", price: "$100.000", order: 8 },
  { category: "Rituales de Renovación", name: "Ritual de Renovación Energética", description: "Tina caliente, con sal del Himalaya y masaje relajante.", duration: "80 min", price: "$95.000", order: 9 },
  // Faciales y Jacuzzi
  { category: "Faciales y Jacuzzi", name: "Baño relajante en Jacuzzi", description: "Jacuzzi individual con sales aromáticas.", duration: "50 min", price: "$18.000", order: 1 },
  { category: "Faciales y Jacuzzi", name: "Hidratación Profunda", description: "Hidratación y relajación.", duration: "30 min", price: "$55.000", order: 2 },
  { category: "Faciales y Jacuzzi", name: "Facial Descongestionante Post Sol", description: "Mascarilla calmante con suero revitalizante.", duration: "80 min", price: "$80.000", order: 3 },
  { category: "Faciales y Jacuzzi", name: "Facial Completo Alunco", description: "Limpieza, exfoliación y máscara de ampolla nutritiva.", duration: "80 min", price: "$80.000", order: 4 },
  { category: "Faciales y Jacuzzi", name: "Facial Completo para Hombre", description: "Limpieza profunda, lavado de barba y aceite suavizante.", duration: "50 min", price: "$60.000", order: 5 },
  { category: "Faciales y Jacuzzi", name: "Facial de Rejuvenecimiento", description: "Energizante y restaurador.", duration: "80 min", price: "$80.000", order: 6 },
  { category: "Faciales y Jacuzzi", name: "Facial Deluxe", description: "Potencia la espiración celular y brillo de la piel.", duration: "50 min", price: "$65.000", order: 7 },
  // Peluquería y Manicure
  { category: "Peluquería y Manicure", name: "Lavado de Pelo", description: "Servicio básico de limpieza capilar.", duration: "--", price: "$15.000", order: 1 },
  { category: "Peluquería y Manicure", name: "Planchado de Pelo Largo", description: "Alisado con plancha para cabello largo.", duration: "--", price: "$25.000", order: 2 },
  { category: "Peluquería y Manicure", name: "Planchado Corto", description: "Alisado con plancha para cabello corto.", duration: "--", price: "$18.000", order: 3 },
  { category: "Peluquería y Manicure", name: "Brushing Largo", description: "Secado y moldeado para cabello largo.", duration: "--", price: "$25.000", order: 4 },
  { category: "Peluquería y Manicure", name: "Brushing Corto", description: "Secado y moldeado para cabello corto.", duration: "--", price: "$18.000", order: 5 },
  { category: "Peluquería y Manicure", name: "Masaje Capilar Largo", description: "Incluye spa de pies para cabello largo.", duration: "--", price: "$28.000", order: 6 },
  { category: "Peluquería y Manicure", name: "Masaje Capilar Corto", description: "Incluye spa de pies para cabello corto.", duration: "--", price: "$24.000", order: 7 },
  { category: "Peluquería y Manicure", name: "Manicure Permanente", description: "Esmaltado de larga duración.", duration: "--", price: "$25.000", order: 8 },
  { category: "Peluquería y Manicure", name: "Manicure Permanente con Diseño", description: "Esmaltado de larga duración con arte decorativo.", duration: "--", price: "$28.000", order: 9 },
  { category: "Peluquería y Manicure", name: "Retiro de Esmalte Permanente", description: "Remoción técnica de esmaltado previo.", duration: "--", price: "$6.000", order: 10 },
  // Circuitos de Agua
  { category: "Circuitos de Agua", name: "Circuito Alunco", description: "Masaje Alunco, aromaterapia y musicoterapia.", duration: "50 min", price: "$80.000", order: 1 },
  { category: "Circuitos de Agua", name: "Circuito Enamorados", description: "Masaje Serenidad, aromaterapia y musicoterapia.", duration: "50 min", price: "$70.000", order: 2 },
  { category: "Circuitos de Agua", name: "Circuito Amistad", description: "Champi Hindú, aromaterapia y musicoterapia.", duration: "30 min", price: "$50.000", order: 3 },
  { category: "Circuitos de Agua", name: "Circuito Súper Mamá", description: "Reflexología podal, masaje capilar, aromaterapia y musicoterapia.", duration: "30 min", price: "$80.000", order: 4 },
  { category: "Circuitos de Agua", name: "Circuito Para Ellos", description: "Facial completo para hombre, aromaterapia y musicoterapia.", duration: "50 min", price: "$80.000", order: 5 },
  { category: "Circuitos de Agua", name: "Circuito Trabajólico", description: "Masaje recarga vital, aromaterapia y musicoterapia.", duration: "50 min", price: "$80.000", order: 6 },
  { category: "Circuitos de Agua", name: "Circuito Relax", description: "Masaje relajante, aromaterapia y musicoterapia.", duration: "50 min", price: "$70.000", order: 7 },
  { category: "Circuitos de Agua", name: "Circuito Tonificante", description: "Masaje descontracturante, aromaterapia y musicoterapia.", duration: "50 min", price: "$90.000", order: 8 },
];

export const seedSpaSchedules = [
  { venue: "Spa", hours: "09:30 - 20:00" },
  { venue: "Tratamientos", hours: "11:00 - 19:00" },
  { venue: "Peluquería", hours: "09:00 - 16:30" },
];

export const seedGymClasses = [
  { name: "Clase de Yoga", description: "Clase guiada de yoga suave enfocada en respiración y estiramiento.", price: "$15.000", schedule: "8:30 - 9:30", order: 1 },
  { name: "Entrenamiento para Trekking", description: "Sesión dinámica adaptada al entorno de altura para mejorar el rendimiento físico.", price: "Incluido", schedule: "Consultar horario", order: 2 },
  { name: "Aquagym", description: "Ejercicios en el agua que combinan actividad aeróbica y resistencia de bajo impacto.", price: "Incluido", schedule: "Consultar horario", order: 3 },
  { name: "Activación Corporal", description: "Sesión guiada para comenzar el día activando el cuerpo y fortaleciendo músculos.", price: "Incluido", schedule: "Consultar horario", order: 4 },
];

export const seedRestaurantItems = [
  // ARBOLEDA - Vinos
  { restaurant: "arboleda", category: "Vinos", subcategory: "Burbujas del mundo", name: "Imperial Brut, Moët & Chandon, Francia", price: "$158.000", order: 1 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Burbujas del mundo", name: "Dom Pérignon, Möet & Chandon, Francia", price: "$450.000", order: 2 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Burbujas del mundo", name: "Hera, Calyptra, Cachapoal Andes", price: "$35.000", order: 3 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Burbujas del mundo", name: "Cordillera, Extra Brut, Miguel Torres, Curicó", price: "$28.500", order: 4 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Burbujas del mundo", name: "Chandon Brut, Luján de Cuyo", price: "$28.000", order: 5 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Sauvignon Blanc", name: "Cipreses, Casa Marín, San Antonio", price: "$35.000", order: 6 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Sauvignon Blanc", name: "Outer Limits, Montes, Petorca", price: "$29.000", order: 7 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Chardonnay", name: "Tara, Ventisquero, Atacama", price: "$55.000", order: 8 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Chardonnay", name: "Los Parientes, Pandolfi Price, Itata", price: "$35.000", order: 9 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Carmenere", name: "Carmín de Peumo, Concha y Toro, Cachapoal", price: "$150.000", order: 10 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Carmenere", name: "El Incidente, Viu Manent, Colchagua", price: "$78.000", order: 11 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Cabernet Sauvignon", name: "Manso de Velasco, Miguel Torres, Maule", price: "$90.000", order: 12 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Cabernet Sauvignon", name: "Enclave, Ventisquero, Maipo", price: "$72.000", order: 13 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Vinos Memorables", name: "Chadwick, Cabernet Sauvignon, Maipo", price: "$590.000", order: 14 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Vinos Memorables", name: "Almaviva, Ensamblaje, Maipo", price: "$350.000", order: 15 },
  { restaurant: "arboleda", category: "Vinos", subcategory: "Vinos Memorables", name: "Don Melchor, Cabernet Sauvignon, Maipo", price: "$330.000", order: 16 },
  // ARBOLEDA - Bebidas Calientes
  { restaurant: "arboleda", category: "Bebidas Calientes", subcategory: null, name: "Americano doble", price: "$3.200", order: 1 },
  { restaurant: "arboleda", category: "Bebidas Calientes", subcategory: null, name: "Cortado simple", price: "$2.900", order: 2 },
  { restaurant: "arboleda", category: "Bebidas Calientes", subcategory: null, name: "Espresso / Ristreto / Lungo / Americano", price: "$1.900 - $2.500", order: 3 },
  // LA GRIETA - Comida
  { restaurant: "lagrieta", category: "Hamburguesas", subcategory: null, name: "Burger de la Casa", description: "Pan Brioche de papa, triple cheddar, 180 grs. smash, pepinillo.", price: "$13.900", order: 1 },
  { restaurant: "lagrieta", category: "Hamburguesas", subcategory: null, name: "Beyond Burger", description: "Vegan Burger, rúcula, duxelle de setas, cebolla asada, salsa de ajo.", price: "$14.900", order: 2 },
  { restaurant: "lagrieta", category: "Hamburguesas", subcategory: null, name: "Burger Serrano & Azul", description: "Jamón serrano, mermelada membrillo, queso azul, mostaza Dijon.", price: "$14.900", order: 3 },
  { restaurant: "lagrieta", category: "Hamburguesas", subcategory: null, name: "Cheese Burger", description: "Clásica hamburguesa con queso cheddar.", price: "$9.900", order: 4 },
  { restaurant: "lagrieta", category: "Sándwiches", subcategory: null, name: "Barros Luco", description: "Filete grillado, queso fundido, mayo merquén en marraqueta.", price: "$8.900", order: 1 },
  { restaurant: "lagrieta", category: "Sándwiches", subcategory: null, name: "Completo Encurtido", description: "Salchicha artesanal, palta, relish pepino, mayo-ajo en pan Nan/Brioche.", price: "$7.900", order: 2 },
  { restaurant: "lagrieta", category: "Sándwiches", subcategory: null, name: "Don Panchito", description: "Filete de pollo, queso, salsa macha, choclo y pebre en marraqueta.", price: "$6.990", order: 3 },
  { restaurant: "lagrieta", category: "Fast Food", subcategory: null, name: "Papas Fritas", description: "Tradicionales sazonadas con sal (Medianas / Grandes).", price: "$4.900 / $5.900", order: 1 },
  { restaurant: "lagrieta", category: "Fast Food", subcategory: null, name: "Papas Cheddar", description: "Con salsa cheddar, tocino crocante y perejil.", price: "$6.900", order: 2 },
  { restaurant: "lagrieta", category: "Fast Food", subcategory: null, name: "Empanadas de Queso", description: "6 unidades fritas acompañadas de pebre.", price: "$8.900", order: 3 },
  { restaurant: "lagrieta", category: "Tablas", subcategory: null, name: "Mar y Tierra", description: "Base de papas, lomo res, pollo, navajuelas, ostiones y camarones.", price: "$23.500", order: 1 },
  { restaurant: "lagrieta", category: "Tablas", subcategory: null, name: "Tabla de Empanadas", description: "16 unidades de empanadas de la casa al horno.", price: "$9.500", order: 2 },
  { restaurant: "lagrieta", category: "Ensaladas", subcategory: null, name: "Ensalada del Chef", description: "Hojas verdes, jamón serrano, aceto miel, frutillas y mozzarella.", price: "$9.900", order: 1 },
  { restaurant: "lagrieta", category: "Ensaladas", subcategory: null, name: "Ensalada César", description: "Pollo grillado, hojas verdes, anchoas, crutones y palta.", price: "$8.900", order: 2 },
  // LA GRIETA - Coctelería
  { restaurant: "lagrieta", category: "Coctelería", subcategory: "Cítricos", name: "Margarita", description: "Don Julio, Gran Manier, jugo de limón.", price: "$9.900", order: 1 },
  { restaurant: "lagrieta", category: "Coctelería", subcategory: "Cítricos", name: "Chardonnay Sour", description: "Chardonnay, limón natural, sirop de la casa.", price: "$7.500", order: 2 },
  { restaurant: "lagrieta", category: "Coctelería", subcategory: "Cítricos", name: "Pisco Sour", description: "Gobernador 40°, jugo de limón, sirop.", price: "$7.500", order: 3 },
  { restaurant: "lagrieta", category: "Coctelería", subcategory: "Históricos", name: "Godfather", description: "Whisky Grants 12 años, Dissarono Amaretto, angostura.", price: "$8.500", order: 4 },
  { restaurant: "lagrieta", category: "Coctelería", subcategory: "Históricos", name: "Negroni", description: "Gin Tanqueray, Campari y Vermuth Rosso.", price: "$8.000", order: 5 },
  { restaurant: "lagrieta", category: "Coctelería", subcategory: "Autor", name: "Carpintero", description: "Pisco, licor de mora/boysenberry, limón, agua de rosas.", price: "$10.900", order: 6 },
  { restaurant: "lagrieta", category: "Coctelería", subcategory: "Autor", name: "Fuego & Flor", description: "Gin, Vermut Rosso, Campari, rosa mosqueta, ahumado de pino.", price: "$9.900", order: 7 },
  { restaurant: "lagrieta", category: "Coctelería", subcategory: "Refrescantes", name: "Aperol Spritz", description: "Aperol, espumante de la zona, top soda.", price: "$7.900", order: 8 },
  { restaurant: "lagrieta", category: "Coctelería", subcategory: "Refrescantes", name: "Moscow Mule", description: "Vodka, jugo de limón natural, Ginger Beer.", price: "$8.500", order: 9 },
  { restaurant: "lagrieta", category: "Destilados y Licores", subcategory: null, name: "Pisco", description: "Waqar 40° / Bou Legado", price: "$5.500 a $9.900", order: 1 },
  { restaurant: "lagrieta", category: "Destilados y Licores", subcategory: null, name: "Whisky", description: "J.W. Blue Label / Akashi / Chivas 18 / Jack Daniel's", price: "$5.000 a $55.000", order: 2 },
  { restaurant: "lagrieta", category: "Destilados y Licores", subcategory: null, name: "Gin", description: "Mary Le Bone / Hendrick's / Tanqueray", price: "$6.000 a $14.500", order: 3 },
  { restaurant: "lagrieta", category: "Cervezas y Sin Alcohol", subcategory: null, name: "Cervezas", description: "Kunstmann / Tamango / Shangrila / Prócer / Kross", price: "$4.500 a $6.500", order: 1 },
  { restaurant: "lagrieta", category: "Cervezas y Sin Alcohol", subcategory: null, name: "Sin Alcohol", description: "Virgin Mary / Virgin Colada / Limonadas / Jugos", price: "$4.500 a $6.800", order: 2 },
  // MUFFIN CAFÉ
  { restaurant: "muffin", category: "Pastelería", subcategory: null, name: "Barra de proteína", price: "$3.500", order: 1 },
  { restaurant: "muffin", category: "Pastelería", subcategory: null, name: "Muffin variedades", price: "$3.200", order: 2 },
  { restaurant: "muffin", category: "Pastelería", subcategory: null, name: "Galletón variedades", price: "$2.500", order: 3 },
  { restaurant: "muffin", category: "Pastelería", subcategory: null, name: "Masa Danesa Rellena de crema", price: "$2.500", order: 4 },
  { restaurant: "muffin", category: "Pastelería", subcategory: null, name: "Donuts variedad sabores", price: "$1.800", order: 5 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Chocolate caliente", price: "$4.900", order: 1 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Moccaccino", price: "$3.900", order: 2 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Café expreso doble", price: "$3.400", order: 3 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Café latte", price: "$3.400", order: 4 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Café cortado", price: "$3.200", order: 5 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Café capucchino", price: "$3.200", order: 6 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Infusiones", price: "$3.000", order: 7 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Café macchiato", price: "$2.800", order: 8 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Lungo", price: "$2.400", order: 9 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Café americano", price: "$2.300", order: 10 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Ristretto", price: "$2.300", order: 11 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Café expreso simple", price: "$2.200", order: 12 },
  { restaurant: "muffin", category: "Bebidas Calientes", subcategory: null, name: "Té variedades", price: "$2.000", order: 13 },
  { restaurant: "muffin", category: "Bebidas Frías", subcategory: null, name: "RedBull variedades", price: "$3.500", order: 1 },
  { restaurant: "muffin", category: "Bebidas Frías", subcategory: null, name: "Acqua Panna 500 cc", price: "$3.200", order: 2 },
  { restaurant: "muffin", category: "Bebidas Frías", subcategory: null, name: "San Pellegrino 500 cc", price: "$3.200", order: 3 },
  { restaurant: "muffin", category: "Bebidas Frías", subcategory: null, name: "Bebidas lata variedades", price: "$2.500", order: 4 },
  { restaurant: "muffin", category: "Bebidas Frías", subcategory: null, name: "Vitamin Water", price: "$1.900", order: 5 },
];

export const seedActivities = [
  // VERANO - Caminatas
  { season: "verano", category: "Caminatas y Trekkings", name: "Fumarolas", description: "Caminata desde el hotel hacia zonas de altura, atravesando bosque nativo hasta llegar a impresionantes fumarolas volcánicas.\nDuración: 3 horas\nAltitud: 2.300 msnm\nDificultad: Media / Alta\nDistancia: 5 km\nCapacidad: 8 pasajeros por guía", order: 1 },
  { season: "verano", category: "Caminatas y Trekkings", name: "Rukapiren", description: "Ruta en medio de bosque nativo que conduce hasta una cascada de 50 metros.\nDuración: 3 horas\nAltitud: 1.000 msnm\nDificultad: Media\nDistancia: 4 km", order: 2 },
  { season: "verano", category: "Caminatas y Trekkings", name: "El Regalo", description: "Caminata desde el hotel hacia la ruta de las cascadas, finalizando en el mirador El Regalo, con vistas panorámicas.\nDuración: 3 horas\nAltitud: 1.300 msnm\nDificultad: Media", order: 3 },
  { season: "verano", category: "Caminatas y Trekkings", name: "Gruta Los Pangues", description: "Sendero fácil y apto para todo público que lleva a una gruta en medio de la naturaleza.\nDuración: 3 horas\nAltitud: 1.200 msnm\nDificultad: Fácil\nDistancia: 2 km", order: 4 },
  { season: "verano", category: "Caminatas y Trekkings", name: "Shangrila", description: "Recorrido por bosque nativo hasta un escorial de lava, testimonio de antiguas erupciones volcánicas.\nDuración: 3 horas\nAltitud: 1.550 msnm\nDificultad: Media", order: 5 },
  { season: "verano", category: "Caminatas y Trekkings", name: "Caminata Nocturna", description: "Exploración guiada del bosque cercano al hotel en horario nocturno, utilizando linternas.\nDuración: 1,5 horas\nAltitud: 1.600 msnm\nDificultad: Fácil\nDistancia: 1,6 km", order: 6 },
  { season: "verano", category: "Caminatas y Trekkings", name: "Laguna El Huemul (Full Day)", description: "Trekking de alta exigencia que atraviesa bosques y terreno volcánico hasta llegar a una laguna de montaña.\nDuración: 8 horas\nAltitud: 2.000 msnm\nDificultad: Alta\nDistancia: 15 km\nOperado por proveedor externo (costo adicional).", order: 7 },
  { season: "verano", category: "Caminatas y Trekkings", name: "Aguas Calientes (Full Day)", description: "Ruta de alta montaña que culmina en un valle con aguas termales naturales.\nDuración: 8 horas\nAltitud: 2.400 msnm\nDificultad: Alta\nOperado por proveedor externo (costo adicional).", order: 8 },
  // VERANO - Bicicleta
  { season: "verano", category: "Bicicleta", name: "Los Coltrahues", description: "Recorrido suave por senderos rodeados de naturaleza, con vistas al valle Las Trancas.\nDuración: 3 horas\nDificultad: Fácil\nDistancia: 9 km", order: 1 },
  { season: "verano", category: "Bicicleta", name: "Rukapiren", description: "Ruta en bicicleta a través de bosque nativo que conduce hasta la cascada Rukapirén.\nDuración: 3 horas\nDificultad: Fácil\nDistancia: 5 km", order: 2 },
  { season: "verano", category: "Bicicleta", name: "Refugio Garganta del Diablo", description: "Ruta que atraviesa bosque centenario y arenales volcánicos hasta un refugio con vista panorámica.\nDuración: 5 horas\nDificultad: Alta\nDistancia: 7 km", order: 3 },
  // VERANO - Contemplación
  { season: "verano", category: "Contemplación y Recreación", name: "Observación de Aves y Fauna", description: "Actividad guiada en el entorno del bosque para aprender a identificar especies y conectar con la biodiversidad local.\nDuración: 2 horas\nDificultad: Fácil", order: 1 },
  { season: "verano", category: "Contemplación y Recreación", name: "Tour Astronómico", description: "Experiencia nocturna con introducción a la astronomía y observación de astros mediante telescopio.\nDuración: 1 hora\nDificultad: Fácil", order: 2 },
  { season: "verano", category: "Contemplación y Recreación", name: "Arborismo", description: "Circuito de aventura en altura con plataformas y puentes colgantes entre árboles.\nDuración: 1 hora\nDificultad: Fácil", order: 3 },
  { season: "verano", category: "Contemplación y Recreación", name: "Canopy Infantil", description: "Actividad de tirolesa diseñada para niños, combinando aventura y seguridad.\nDuración: 1 hora\nDificultad: Fácil\nCapacidad: 6 niños por guía", order: 4 },
  // VERANO - Bienestar
  { season: "verano", category: "Bienestar y Talleres", name: "Yoga", description: "Práctica que conecta cuerpo, respiración y mente, mejorando flexibilidad y equilibrio.\nDuración: 1 hora\nCapacidad: 16 participantes", order: 1 },
  { season: "verano", category: "Bienestar y Talleres", name: "Activación Corporal", description: "Sesión guiada para comenzar el día activando el cuerpo y fortaleciendo músculos.\nDuración: 1 hora", order: 2 },
  { season: "verano", category: "Bienestar y Talleres", name: "Taller de Arte", description: "Espacio creativo familiar enfocado en la exploración artística inspirada en la naturaleza.\nDuración: 1 hora", order: 3 },
  { season: "verano", category: "Bienestar y Talleres", name: "Taller de Coctelería", description: "Experiencia guiada para aprender técnicas básicas de coctelería y degustar preparaciones.\nDuración: 1 hora", order: 4 },
  { season: "verano", category: "Bienestar y Talleres", name: "Taller de Pizza", description: "Actividad culinaria familiar: aprende a preparar tu pizza a la piedra.\nDuración: 1 hora\nDías: Jueves y sábado", order: 5 },
  { season: "verano", category: "Bienestar y Talleres", name: "Música en Vivo / Karaoke", description: "Actividad nocturna en el Bar La Grieta con música en vivo.\nJueves, viernes y sábado desde las 22:00", order: 6 },
  // INVIERNO
  { season: "invierno", category: "Deportes de Nieve", name: "Ski y Snowboard", description: "Disfruta de la nieve en pistas de nivel internacional, ideales para principiantes y expertos.\nAltitud: 1.540 – 2.400 msnm\nDificultad: Todas las categorías", order: 1 },
  { season: "invierno", category: "Deportes de Nieve", name: "Motos de Nieve", description: "Recorre paisajes nevados a través de bosques y laderas en una experiencia llena de adrenalina. Consultar en recepción.", order: 2 },
  { season: "invierno", category: "Deportes de Nieve", name: "Heli-Ski", description: "Accede a cumbres remotas en helicóptero y desciende por nieve virgen fuera de pista. Consultar en recepción.", order: 3 },
  { season: "invierno", category: "Exploración & Naturaleza", name: "Caminatas con Raquetas (Día)", description: "Recorridos guiados por bosques nevados que permiten explorar la montaña de forma accesible.", order: 1 },
  { season: "invierno", category: "Exploración & Naturaleza", name: "Caminatas con Raquetas (Noche)", description: "Experiencia nocturna en la nieve que permite descubrir el paisaje bajo una atmósfera única.", order: 2 },
  { season: "invierno", category: "Bienestar e Indoor", name: "Piscina Temperada", description: "Relájate en piscinas de aguas termales provenientes de la montaña.", order: 1 },
  { season: "invierno", category: "Bienestar e Indoor", name: "Spa y Wellness", description: "Espacio integral de bienestar con tratamientos, sauna, baños de vapor.", order: 2 },
  { season: "invierno", category: "Bienestar e Indoor", name: "Yoga y Activación Física", description: "Actividades guiadas que combinan movimiento, respiración y conexión con el entorno.", order: 3 },
  // Otras Actividades (verano)
  { season: "verano", category: "Otras Actividades", name: "Canchas de Tenis", description: "Canchas de tenis disponibles para todos los huéspedes del hotel.\nEquipos disponibles en recepción.\nReserva en recepción o anexo 3540.", order: 1 },
  { season: "verano", category: "Otras Actividades", name: "Granja Educativa", description: "Experiencia interactiva donde los niños y adultos pueden conocer y compartir con animales de granja.\nDuración: 1 hora.", order: 2 },
  { season: "verano", category: "Otras Actividades", name: "Cabalgatas", description: "Paseo a caballo por los senderos del entorno del hotel, con guía especializado.\nDuración: 1 hora\nConsultar en recepción.", price: "Con costo adicional", order: 3 },
  // Otras Actividades (invierno)
  { season: "invierno", category: "Otras Actividades", name: "Canchas de Tenis", description: "Canchas de tenis disponibles para todos los huéspedes del hotel.\nEquipos disponibles en recepción.\nReserva en recepción o anexo 3540.", order: 1 },
];

export const seedFamilyPrograms = [
  { type: "club", name: "Club de la Montaña", description: "Programa con actividades recreativas y educativas enfocadas en la exploración, el juego y la conexión con la naturaleza. Desde los 7 años de edad.", order: 1 },
  { type: "club", name: "Mini Kids Club", description: "Programa recreativo desde los 4 años hasta los 7 años de edad.", order: 2 },
  { type: "club", name: "Salón de Juegos", description: "Espacio de entretención y recreación para toda la familia.\nHorarios: 08:30 a 23:30 horas.\nContacto: Anexo 3540.", schedule: "08:30 - 23:30", order: 3 },
  { type: "guarderia", name: "Guardería", description: "Servicio para niños/as de 3 a 7 años con control de esfínter. Lunes a Sábado.\nHorario: 08:30 a 18:30 hrs\nDomingo: 8:30 a 16:30 hrs", schedule: "Lun-Sáb: 08:30-18:30 | Dom: 08:30-16:30", order: 1 },
  { type: "actividad", name: "Canopy Infantil", description: "Actividad de tirolesa diseñada para niños, combinando aventura y seguridad.\nDuración: 1 hora | Capacidad: 6 niños por guía", season: "verano", order: 1 },
  { type: "actividad", name: "Granja Educativa", description: "Experiencia interactiva donde los niños pueden conocer y compartir con animales de granja.\nDuración: 1 hora", season: "verano", order: 2 },
  { type: "actividad", name: "Tour Astronómico", description: "Experiencia nocturna con introducción a la astronomía y observación de astros.\nDuración: 1 hora", season: "verano", order: 3 },
  { type: "actividad", name: "Taller de Arte", description: "Espacio creativo familiar enfocado en la exploración artística.\nDuración: 1 hora", season: "verano", order: 4 },
  { type: "actividad", name: "Taller de Pizza", description: "Actividad culinaria familiar, aprenden a preparar su pizza.\nJueves y sábado", season: "invierno", order: 1 },
  { type: "actividad", name: "Juegos en la Piscina", description: "Espacio recreativo con actividades acuáticas grupales.", season: "invierno", order: 2 },
];

export const seedRoomProducts = [
  // Cuidado Personal
  { category: "Cuidado Personal e Higiene", name: "Cepillo dental", price: "$3.000", order: 1 },
  { category: "Cuidado Personal e Higiene", name: "Preservativos", price: "$3.000", order: 2 },
  { category: "Cuidado Personal e Higiene", name: "Crema de afeitar", price: "$8.000", order: 3 },
  { category: "Cuidado Personal e Higiene", name: "Desodorante", price: "$3.000", order: 4 },
  { category: "Cuidado Personal e Higiene", name: "Kit dental-pasta (pequeño)", price: "$2.000", order: 5 },
  { category: "Cuidado Personal e Higiene", name: "Pasta de dientes", price: "$3.000", order: 6 },
  { category: "Cuidado Personal e Higiene", name: "Quita esmalte", price: "$6.000", order: 7 },
  { category: "Cuidado Personal e Higiene", name: "Tampones", price: "$5.000", order: 8 },
  { category: "Cuidado Personal e Higiene", name: "Toalla higiénica", price: "$5.000", order: 9 },
  { category: "Cuidado Personal e Higiene", name: "Toallita húmeda", price: "$2.000", order: 10 },
  { category: "Cuidado Personal e Higiene", name: "Afeitadora desechable", price: "$2.000", order: 11 },
  { category: "Cuidado Personal e Higiene", name: "Peineta/cepillo de pelo", price: "$5.000", order: 12 },
  { category: "Cuidado Personal e Higiene", name: "Corta uñas", price: "$5.000", order: 13 },
  { category: "Cuidado Personal e Higiene", name: "Tapones oído", price: "$1.000", order: 14 },
  // Bebés y Niños
  { category: "Bebés y Niños", name: "Guatero semillas niños", price: "$6.000", order: 1 },
  { category: "Bebés y Niños", name: "Mamadera", price: "$5.000", order: 2 },
  { category: "Bebés y Niños", name: "Escobilla limpia mamadera", price: "$5.000", order: 3 },
  { category: "Bebés y Niños", name: "Pañal bebé", price: "$5.000", order: 4 },
  { category: "Bebés y Niños", name: "Pañales piscina", price: "$1.500", order: 5 },
  { category: "Bebés y Niños", name: "Chupete bebé", price: "$3.000", order: 6 },
  // Electrónica
  { category: "Electrónica y Accesorios", name: "Adaptador tierra", price: "$5.000", order: 1 },
  { category: "Electrónica y Accesorios", name: "Adaptador simple", price: "$3.000", order: 2 },
  { category: "Electrónica y Accesorios", name: "Adaptador universal", price: "$10.000", order: 3 },
  { category: "Electrónica y Accesorios", name: "Pilas AA y AAA", price: "$2.000", order: 4 },
  { category: "Electrónica y Accesorios", name: "Bolsa reductora ropa", price: "$3.000", order: 5 },
  // Vestuario
  { category: "Vestuario y Accesorios", name: "Anteojos 2.0/2.5", price: "$10.000", order: 1 },
  { category: "Vestuario y Accesorios", name: "Antiojera vichy", price: "$2.000", order: 2 },
  { category: "Vestuario y Accesorios", name: "Cintillo azul cotele", price: "$5.000", order: 3 },
  { category: "Vestuario y Accesorios", name: "Calcetines", price: "$2.000", order: 4 },
  { category: "Vestuario y Accesorios", name: "Capa de agua biodegradable", price: "$5.000", order: 5 },
  { category: "Vestuario y Accesorios", name: "Capa de agua gruesa", price: "$10.000", order: 6 },
  // Piscina
  { category: "Piscina y Deporte", name: "Pañales piscina", price: "$1.500", order: 1 },
  { category: "Piscina y Deporte", name: "Gorra natación", price: "$2.000", order: 2 },
  { category: "Piscina y Deporte", name: "Botella 500ml policarbonato", price: "$4.000", order: 3 },
];

export const seedRoomInfo = [
  { section: "housekeeping", title: "Housekeeping", content: "Horario: 08:30 a 23:00 hrs\n\nNuestro equipo de mucamas está disponible para mantener tu habitación en perfectas condiciones durante tu estadía.", order: 1 },
  { section: "lavanderia", title: "Lavandería", content: "Horario: 08:30 a 16:00 hrs\n\nServicio de lavandería disponible. Consulta tarifas y horarios en recepción.", order: 2 },
  { section: "emergencia", title: "Emergencias Médicas", content: "Asistencia 24/7: Si requiere atención médica, comuníquese con recepción marcando el anexo 3500 desde su habitación.\n\nContacto externo: +562 2322 3500", order: 3 },
  { section: "caja", title: "Caja de Seguridad", content: "Cada habitación dispone de una caja de seguridad para el resguardo de objetos de valor.\n\nEn caso de inconvenientes con la clave de acceso, contacte a recepción para recibir ayuda del personal técnico.", order: 4 },
  { section: "protocolo", title: "Protocolo de Seguridad", content: "Las emergencias se notificarán mediante alarma sonora o llamada desde el lobby.\n\nMantenga la calma y siga las indicaciones del personal. En el interior de la puerta encontrará un plano con las vías de escape.\n\nDurante incendios o sismos está prohibido el uso de ascensores: use las escaleras.\n\nZonas de Seguridad:\n• Zona A: Comedor Arboleda (costado lobby)\n• Zona B: Lobby Centro de Convenciones\n• Zona C: Entrada lobby principal\n• Zona D: Exterior entrada Centro de Convenciones", order: 5 },
];

export const seedAlerts: { title: string; message: string; type: string }[] = [];
